"""init: rebuild database

Revision ID: cf44c714dae1
Revises: 
Create Date: 2026-03-03 22:53:09.504590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf44c714dae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client_type', sa.Enum('INDIVIDUAL', 'COMPANY', name='clienttype'), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_tax_id'), 'clients', ['tax_id'], unique=True)
    op.create_table('locations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_code', sa.String(length=20), nullable=False),
    sa.Column('location_type', sa.Enum('PORT', 'WAREHOUSE', 'DEPOT', 'YARD', 'OFFICE', name='locationtype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_location_code'), 'locations', ['location_code'], unique=True)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('ports',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('port_type', sa.Enum('SEA', 'RIVER', 'LAKE', name='porttype'), nullable=False),
    sa.Column('max_vessel_draft', sa.Float(), nullable=True),
    sa.Column('container_terminals', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_code'), 'ports', ['code'], unique=True)
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.create_index(op.f('ix_ports_name'), 'ports', ['name'], unique=False)
    op.create_table('vessels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('imo_number', sa.String(length=10), nullable=False),
    sa.Column('flag_country', sa.String(length=50), nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=False),
    sa.Column('deadweight_tonnage', sa.Integer(), nullable=False),
    sa.Column('gross_tonnage', sa.Integer(), nullable=False),
    sa.Column('length_overall', sa.Float(), nullable=True),
    sa.Column('beam', sa.Float(), nullable=True),
    sa.Column('draft', sa.Float(), nullable=True),
    sa.Column('max_containers', sa.Integer(), nullable=True),
    sa.Column('max_cargo_weight', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED', name='vesselstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_id'), 'vessels', ['id'], unique=False)
    op.create_index(op.f('ix_vessels_imo_number'), 'vessels', ['imo_number'], unique=True)
    op.create_index(op.f('ix_vessels_name'), 'vessels', ['name'], unique=False)
    op.create_table('containers',
    sa.Column('container_number', sa.String(length=11), nullable=False),
    sa.Column('container_type', sa.Enum('DRY_20', 'DRY_40', 'REEFER_20', 'REEFER_40', 'OPEN_TOP', 'FLAT_RACK', 'TANK', name='containertype'), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=False),
    sa.Column('max_volume', sa.Float(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('current_volume', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('EMPTY', 'LOADED', 'IN_TRANSIT', 'AT_PORT', 'DELIVERED', 'DAMAGED', 'MAINTENANCE', name='containerstatus'), nullable=False),
    sa.Column('current_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_container_number'), 'containers', ['container_number'], unique=True)
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'TERMINATED', 'SUSPENDED', name='contractstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('personnel',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('GLOBAL_ADMIN', 'LOCATION_MANAGER', 'LOGISTICS_OPERATOR', 'PORT_PERSONNEL', 'ADMINISTRATIVE', 'AUDITOR', name='personnelrole'), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_email'), 'personnel', ['email'], unique=True)
    op.create_index(op.f('ix_personnel_employee_id'), 'personnel', ['employee_id'], unique=True)
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('route_code', sa.String(length=20), nullable=False),
    sa.Column('departure_port_id', sa.UUID(), nullable=False),
    sa.Column('arrival_port_id', sa.UUID(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SEASONAL', name='routestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['departure_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_index(op.f('ix_routes_route_code'), 'routes', ['route_code'], unique=True)
    op.create_table('shipments',
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('bill_of_lading', sa.String(length=50), nullable=True),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'BOOKED', 'LOADING', 'IN_TRANSIT', 'AT_PORT', 'UNLOADING', 'COMPLETED', 'CANCELLED', 'DELAYED', name='shipmentstatus'), nullable=False),
    sa.Column('total_containers', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_bill_of_lading'), 'shipments', ['bill_of_lading'], unique=True)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_table('cargo',
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cargo_type', sa.Enum('GENERAL', 'PERISHABLE', 'DANGEROUS', 'FRAGILE', 'LIQUID', 'BULK', name='cargotype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), nullable=True),
    sa.Column('temperature_required', sa.Float(), nullable=True),
    sa.Column('packaging_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'LOADED', 'IN_TRANSIT', 'DELIVERED', 'DAMAGED', 'LOST', name='cargostatus'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_index(op.f('ix_cargo_tracking_number'), 'cargo', ['tracking_number'], unique=True)
    op.create_table('events',
    sa.Column('event_type', sa.Enum('BOOKING_CREATED', 'CONTAINER_LOADED', 'CONTAINER_UNLOADED', 'VESSEL_DEPARTURE', 'VESSEL_ARRIVAL', 'INSPECTION', 'DAMAGE_REPORTED', 'CUSTOMS_CLEARANCE', 'DELAY_REPORTED', 'STATUS_CHANGE', name='eventtype'), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('personnel_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cargo_tracking_number'), table_name='cargo')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_bill_of_lading'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_routes_route_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_employee_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_email'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_container_number'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_vessels_name'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_imo_number'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_id'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_ports_name'), table_name='ports')
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.drop_index(op.f('ix_ports_code'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_code'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_clients_tax_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
