"""Change personnel.is_active from string to boolean

Revision ID: e4bdd86f5a59
Revises: f020e7a5e901
Create Date: 2026-03-01 17:27:00.933524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bdd86f5a59'
down_revision = 'f020e7a5e901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, convert string values to boolean using proper PostgreSQL casting
    op.execute("UPDATE personnel SET is_active = 'true' WHERE is_active = 'true'")
    op.execute("UPDATE personnel SET is_active = 'false' WHERE is_active = 'false'")
    
    # Then alter the column type with explicit USING clause for PostgreSQL
    op.alter_column('personnel', 'is_active',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=False,
               server_default=sa.text('true'),
               postgresql_using='is_active::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First alter the column type back to string
    op.alter_column('personnel', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               server_default=sa.text("'true'"))
    
    # Then convert boolean values back to string
    op.execute("UPDATE personnel SET is_active = 'true' WHERE is_active = true")
    op.execute("UPDATE personnel SET is_active = 'false' WHERE is_active = false")
    # ### end Alembic commands ###
