"""feat(Rol):Se crea el objeto rol

Revision ID: 06004e9b186e
Revises: 440c579bc893
Create Date: 2026-03-03 00:53:41.748372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06004e9b186e'
down_revision: Union[str, None] = '440c579bc893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
