"""feat(RolUser): creation braking table rol and user

Revision ID: 3c90e5e1fdfd
Revises: 06004e9b186e
Create Date: 2026-03-03 01:03:11.886457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c90e5e1fdfd'
down_revision: Union[str, None] = '06004e9b186e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    # ### end Alembic commands ###
