"""feat(Permission): Its created a Permission db object

Revision ID: 3daa46448bde
Revises: 20673d6ac0ac
Create Date: 2026-03-02 22:16:38.988013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daa46448bde'
down_revision: Union[str, None] = '20673d6ac0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
