"""refactor(Permission): Adds tag and operationId to PermissionModel

Revision ID: 440c579bc893
Revises: 2cb9b31a7b70
Create Date: 2026-03-02 22:45:06.851185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440c579bc893'
down_revision: Union[str, None] = '2cb9b31a7b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('tag', sa.String(length=1000), nullable=True))
    op.add_column('permissions', sa.Column('operationId', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'operationId')
    op.drop_column('permissions', 'tag')
    # ### end Alembic commands ###
