"""fix(Rol): it applies foreign key

Revision ID: 65b73807cdd6
Revises: c647646e5723
Create Date: 2026-03-03 01:18:26.004000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b73807cdd6'
down_revision: Union[str, None] = 'c647646e5723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
