"""feat(RolUser): creation braking table rol and user fix

Revision ID: a8e64a8a541a
Revises: 3c90e5e1fdfd
Create Date: 2026-03-03 01:06:56.575987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e64a8a541a'
down_revision: Union[str, None] = '3c90e5e1fdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
