"""feat(middleTables): Appends is_active to RolUser and UserPermit

Revision ID: c647646e5723
Revises: cd293b285422
Create Date: 2026-03-03 01:12:18.500822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c647646e5723'
down_revision: Union[str, None] = 'cd293b285422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rol_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_permits', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permits', 'is_active')
    op.drop_column('rol_user', 'is_active')
    # ### end Alembic commands ###
