"""feat(UserPermit): Se agrega modelo de user permit

Revision ID: cd293b285422
Revises: a8e64a8a541a
Create Date: 2026-03-03 01:09:13.351797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd293b285422'
down_revision: Union[str, None] = 'a8e64a8a541a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
