events {
    worker_connections 1024;
}

http {
    upstream gateway {
        least_conn;
        server gateway:8080;
    }

    server {
        listen 80;

        # Todo pasa primero por el gateway
        location / {
            proxy_pass http://gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

    }
}
